#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python manage.py collectstatic --noinput
python manage.py makemigrations --noinput
python manage.py migrate --noinput --database=account
python manage.py migrate --noinput --database=forum
python manage.py migrate --noinput --database=tag

python manage.py runserver 0.0.0.0:8000
