# Generated by Django 4.2 on 2023-07-30 10:29

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='', max_length=255)),
                ('content', models.TextField(db_index=True)),
                ('creator_id', models.PositiveIntegerField()),
                ('approver_id', models.PositiveIntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('approver_name', models.CharField(default='', max_length=300)),
                ('approver_email', models.EmailField(default='', max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('approver_type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_threads', to='contenttypes.contenttype')),
                ('creator_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to='contenttypes.contenttype')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='forum.thread')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='ThreadVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('user_name', models.CharField(max_length=300)),
                ('user_email', models.EmailField(max_length=254)),
                ('is_upvote', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated', models.DateTimeField(auto_now=True, db_index=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='forum.thread')),
                ('user_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_votes', to='contenttypes.contenttype')),
            ],
        ),
        migrations.AddIndex(
            model_name='threadvote',
            index=models.Index(fields=['user_type', 'user_id'], name='forum_threa_user_ty_64624d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='threadvote',
            unique_together={('thread', 'user_type', 'user_id')},
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['creator_type', 'creator_id'], name='forum_threa_creator_7809c9_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['approver_type', 'approver_id'], name='forum_threa_approve_976cbf_idx'),
        ),
    ]
