# Generated by Django 4.2 on 2023-07-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='approver_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='user_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
