# Generated by Django 4.2 on 2023-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='creator_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='thread',
            name='creator_name',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='user_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
