# Generated by Django 4.2 on 2023-08-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_thread_creator_email_alter_thread_creator_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='approved',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='thread',
            name='approver_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='thread',
            name='approver_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='thread',
            name='approver_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='thread',
            name='creator_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='thread',
            name='creator_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='user_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
