# Generated by Django 4.2 on 2023-07-30 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('multidbcontenttypes', '0001_initial'),
        ('forum', '0002_alter_thread_approver_id_alter_threadvote_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='approver_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_threads', to='multidbcontenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='thread',
            name='creator_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to='multidbcontenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='threadvote',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thread_votes', to='multidbcontenttypes.contenttype'),
        ),
    ]
