# Generated by Django 4.2 on 2023-07-31 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_alter_thread_approver_type_alter_thread_creator_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='threadvote',
            options={'ordering': ['-created']},
        ),
    ]
