# Generated by Django 4.2 on 2023-08-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_threadcategory_taggedthread_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(),
        ),
    ]
